services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5unN1ng
      MYSQL_DATABASE: iotdb
      MYSQL_USER: iot_5unN1ng
      MYSQL_PASSWORD: 5unN1ng
    ports:
      - "3306:3306"
    volumes:
      - /mnt/g/iot_project/data/mariadb:/var/lib/mysql
    networks:
      - iot_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 5unN1ng
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - iot_net

  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - /mnt/g/iot_project/data/nodered:/data
    depends_on:
      - mariadb
      - influxdb
    networks:
      - iot_net

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: iot_5unN1ng
      DOCKER_INFLUXDB_INIT_PASSWORD: 5unN1ng123
      DOCKER_INFLUXDB_INIT_ORG: iotorg
      DOCKER_INFLUXDB_INIT_BUCKET: iotbucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: supertoken
    ports:
      - "8086:8086"
    volumes:
      - /mnt/g/iot_project/data/influxdb:/var/lib/influxdb2
    networks:
      - iot_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: 5unN1ng
      GF_SECURITY_ADMIN_PASSWORD: 5unN1ng
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - /mnt/g/iot_project/data/grafana:/var/lib/grafana
    networks:
      - iot_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - grafana
      - nodered
      - mariadb
      - influxdb          # ✅ Thêm dòng này để Nginx thấy InfluxDB
    networks:
      - iot_net

networks:
  iot_net:
    driver: bridge
